### ISSUE TITLE
Draft Encounter offline dashboard card showing wrong numbers.

### ISSUE THREAD

**Issue by sachsk** [avniproject/Teach-Nagaland#10] opened 2023-10-26 10:18 UTC
## Context
We have added the draft encounter count card in the offline dashboard ideally, it should show the count of unique individuals which has the draft in their encounters. but now it's showing the same individual multiple times so we need to fix this.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWQwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba9c783123ca11225ac01a123baaec1637df60b5/WhatsApp%20Image%202023-10-26%20at%2015.50.41.jpeg)

## Acceptance  criteria

- [ ] One individual shows/counts only once if has a draft encounter.

## Tech approach 

- In the Draft Observations card return the unique individuals.

**Comment by BEULAHEVANJALIN** [comment] 2023-10-26 12:54
Not able to to reproduce the issue. So moving this forward to QA. 
Also I've tried rewriting the script to return only unique individual objects based on their uuids. If the issue still persists and QA identifies the same problem, we can consider implementing the following updated script.


```
'use strict';
({params, imports}) => {
    const lineListFunction = function () {
        const uniqueIndividualUuids = new Set();
        const uniqueIndividuals = [];
        
        params.db.objects('DraftEncounter').forEach((encounter) => {
            if (!uniqueIndividualUuids.has(encounter.individual.uuid)) {
                uniqueIndividualUuids.add(encounter.individual.uuid);
                uniqueIndividuals.push(encounter.individual);
            }
        });
        
        return uniqueIndividuals;
    };
    const calculateSumOfObservationValues = (params, imports) =>  {
        return lineListFunction().length;
    };
    return {
        primaryValue: calculateSumOfObservationValues(params, imports),
        lineListFunction
    };
};
```

**Comment by Dinesh2019** [comment] 2023-10-26 15:03
The issue is reproducible when we edit the observation and the draft doesn't have the edit scenario as well even though the draft option is enabled.

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME4yQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--53cd149c65cff97a0c17f0fa17f971814b36c2f1/Screen%20Recording%202023-10-26%20at%208.34.33%E2%80%AFPM.mov

**Comment by Dinesh2019** [comment] 2023-10-30 07:10
Depending on the bug card :
https://github.com/avniproject/Teach-Nagaland/issues/10

**Comment by BEULAHEVANJALIN** [comment] 2023-10-31 09:45
@salilsamanvay why is card moved to fresh dev ready?
Can you add the comment please?

**Closed as completed** 2023-11-02 04:54 UTC
